"""Generated brand tokens. Edit design/tokens.json and run npm run tokens:sync."""

BACKGROUND = "#121214"
FOREGROUND = "#F4F2EC"
CARD = "#1A1A1D"
CARD_FOREGROUND = "#F4F2EC"
POPOVER = "#202023"
POPOVER_FOREGROUND = "#F4F2EC"
PRIMARY = "#F97316"
PRIMARY_FOREGROUND = "#121214"
SECONDARY = "#252529"
SECONDARY_FOREGROUND = "#F4F2EC"
MUTED = "#2D2D31"
MUTED_FOREGROUND = "#AAA9B0"
ACCENT = "#4EDEA3"
ACCENT_CONTRAST = "#78F0BD"
ACCENT_FOREGROUND = "#101011"
EDITORIAL = "#121214"
EDITORIAL_2 = "#1E1E21"
INK = "#F4F2EC"
WARM_ACCENT = "#F4B860"
WARM_ACCENT_CONTRAST = "#FFD59A"
SURFACE_DARK = "#0B0B0C"
SURFACE_DARK_2 = "#131315"
SURFACE_DARK_3 = "#1E1E21"
TEXT_ON_DARK = "#F4F2EC"
TEXT_ON_DARK_MUTED = "#B2B1B8"
TEXT_ON_DARK_ACCENT = "#FB923C"
BORDER = "#3A3A3F"
INPUT = "#515157"
RING = "#F97316"
CHART_1 = "#F97316"
CHART_2 = "#4EDEA3"
CHART_3 = "#8D8D96"
CHART_4 = "#38BDF8"
CHART_5 = "#F4B860"
SUCCESS = "#4EDEA3"
WARNING = "#F4B860"
DANGER = "#FF6B5F"

ACCENT_DARK = ACCENT_CONTRAST
ACCENT_LIGHT = TEXT_ON_DARK_ACCENT
WARM_ACCENT_DARK = WARM_ACCENT_CONTRAST
GRID = EDITORIAL_2
CHART4 = CHART_4
CHART_HALF_HEIGHT = 340
CHART_FULL_HEIGHT = 430
CHART_HALF_EMBED_HEIGHT = 320
CHART_FULL_EMBED_HEIGHT = 320
MAP_FULL_HEIGHT = 460
MAP_EMBED_HEIGHT = 330
FONT_FAMILY = "Inter, system-ui, -apple-system, Segoe UI, sans-serif"
HEADING_FONT_FAMILY = "'Hanken Grotesk', Inter, system-ui, sans-serif"
MONO_FONT_FAMILY = "'JetBrains Mono', ui-monospace, SFMono-Regular, Consolas, monospace"
SEQ = [PRIMARY, ACCENT, WARM_ACCENT, CHART4, INK, WARNING, DANGER]
ROUTE_COLORS = [PRIMARY, ACCENT, WARM_ACCENT, CHART4, DANGER, WARNING]
STATUS_COLORS = {
    "No prazo": SUCCESS,
    "Atrasado": DANGER,
    "Em risco": WARNING,
    "Ocorrência aberta": DANGER,
    "Entregue": SUCCESS,
    "Em transito": ACCENT,
    "Em trânsito": ACCENT,
    "Abaixo do piso": WARNING,
    "Abaixo do piso ANTT": DANGER,
}
SEVERITY_COLORS = {
    "Alta": SUCCESS,
    "Média": WARNING,
    "Baixa": DANGER,
    "Baixo": DANGER,
    "Crítico": DANGER,
    "Atenção": WARNING,
    "OK": SUCCESS,
    "Alto": SUCCESS,
}


def maturidade(metodo: str = "heurístico", producao: str = "solver dedicado") -> str:
    return f"Amostra curada · método {metodo} · produção usaria {producao}"
